
import type { Language, WeatherForecast, ActivityLog } from './types';
import { WeatherCondition } from './types';

export const LANGUAGES: { key: Language; name: string }[] = [
  { key: 'en', name: 'English' },
  { key: 'es', name: 'Español' },
  { key: 'de', name: 'Deutsch' },
  { key: 'ja', name: '日本語' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'Agri-Intelli',
    exportCSV: 'Export CSV',
    exportPDF: 'Export PDF',
    fieldMapAnalysis: 'Field Map Analysis',
    vegetationIndices: 'Vegetation Indices',
    keyMetrics: 'Key Metrics',
    activeAlerts: 'Active Alerts',
    weatherForecast: 'Weather Forecast',
    dailyActivityReport: 'Daily Activity Report',
    aiCropSuggestion: 'AI Crop Suggestion',
    noActiveAlerts: 'No active alerts. The farm is healthy.',
    highPestRisk: 'High pest risk detected',
    lowSoilMoisture: 'Low soil moisture detected',
    avgSoilMoisture: 'Avg. Soil Moisture',
    avgNDVI: 'Avg. NDVI',
    canopyCover: 'Canopy Cover',
    cropGrowthStage: 'Crop Growth Stage',
    daysAhead: 'days ahead',
    daysBehind: 'days behind',
    onSchedule: 'on schedule',
    mapLayer: 'Map Layer',
    none: 'None',
    soilMoisture: 'Soil Moisture',
    soilAnalysis: 'Soil Analysis',
    pestRisk: 'Pest Risk',
    legendLow: 'Low',
    legendHigh: 'High',
    uploadImage: 'Upload Image',
    useCamera: 'Use Camera',
    stopCamera: 'Stop Camera',
    capture: 'Capture',
    analyzing: 'Analyzing...',
    errorRecommendations: 'Could not fetch suggestion.',
    loadingRecommendations: 'Generating suggestion...',
    clickRefreshSuggestion: 'Click refresh to get an AI crop suggestion based on current farm conditions.',
    refresh: 'Refresh',
    farmConditions: 'Farm Conditions',
    phLevel: 'pH Level',
    nutrients: 'Nutrients (N-P-K)',
    soilType: 'Soil Type',
    climate: 'Climate',
    currentWeather: 'Current Weather',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    recommendedCrop: 'Recommended Crop',
    justification: 'Justification',
    livePestMonitor: "Live Pest Monitor",
    scanForPests: "Scan for Pests",
    scanning: "Scanning...",
    activityLog: "Activity Log",
    noPestsFound: "No pests found in the current view.",
    startCamera: "Start Camera",
    pestIdentified: "identified",
    actionSprayed: "Pesticide sprayed at",
    automatedScanning: "Automated Scanning",
    automatedSuggestion: "Automated Suggestion",
    plantHealthAnalyst: "Plant Health Analyst",
    plantHeight: "Plant Height",
    leafCount: "Leaf Count",
    soilTemperature: "Soil Temp.",
    analyzePlant: "Analyze Plant",
    analysisResults: "Analysis Results",
    plantHealthStatus: "Plant Health Status",
    growthStage: "Growth Stage",
    stressFactors: "Stress Factors",
    recommendations: "Recommendations",
    growthTrends: "Growth Trends",
    errorAnalysis: "Error during plant analysis.",
    uploadOrCaptureImage: "Upload or capture an image of the plant to analyze.",
    soilHealthScore: "Soil Health Score",
    poor: "Poor",
    fair: "Fair",
    good: "Good",
    excellent: "Excellent",
    getScore: "Get Score",
    generatingScore: "Generating score...",
    errorScore: "Could not fetch score.",
    clickToGetScore: "Click refresh to get an AI-calculated soil health score.",
    automatedScore: "Automated Score",
  },
  es: {
    appTitle: 'Agri-Intelli',
    exportCSV: 'Exportar CSV',
    exportPDF: 'Exportar PDF',
    fieldMapAnalysis: 'Análisis del Mapa de Campo',
    vegetationIndices: 'Índices de Vegetación',
    keyMetrics: 'Métricas Clave',
    activeAlerts: 'Alertas Activas',
    weatherForecast: 'Pronóstico del Tiempo',
    dailyActivityReport: 'Informe de Actividad Diaria',
    aiCropSuggestion: 'Sugerencia de Cultivo por IA',
    noActiveAlerts: 'No hay alertas activas. La granja está sana.',
    highPestRisk: 'Alto riesgo de plagas detectado',
    lowSoilMoisture: 'Baja humedad del suelo detectada',
    avgSoilMoisture: 'Humedad Media del Suelo',
    avgNDVI: 'NDVI Medio',
    canopyCover: 'Cobertura del Dosel',
    cropGrowthStage: 'Etapa de Crecimiento del Cultivo',
    daysAhead: 'días de adelanto',
    daysBehind: 'días de atraso',
    onSchedule: 'según lo previsto',
    mapLayer: 'Capa del Mapa',
    none: 'Ninguna',
    soilMoisture: 'Humedad del Suelo',
    soilAnalysis: 'Análisis del Suelo',
    pestRisk: 'Riesgo de Plagas',
    legendLow: 'Bajo',
    legendHigh: 'Alto',
    uploadImage: 'Subir Imagen',
    useCamera: 'Usar Cámara',
    stopCamera: 'Detener Cámara',
    capture: 'Capturar',
    analyzing: 'Analizando...',
    errorRecommendations: 'No se pudo obtener la sugerencia.',
    loadingRecommendations: 'Generando sugerencia...',
    clickRefreshSuggestion: 'Haga clic en actualizar para obtener una sugerencia de cultivo de IA basada en las condiciones actuales de la granja.',
    refresh: 'Actualizar',
    farmConditions: 'Condiciones de la Granja',
    phLevel: 'Nivel de pH',
    nutrients: 'Nutrientes (N-P-K)',
    soilType: 'Tipo de Suelo',
    climate: 'Clima',
    currentWeather: 'Clima Actual',
    temperature: 'Temperatura',
    humidity: 'Humedad',
    windSpeed: 'Velocidad del Viento',
    recommendedCrop: 'Cultivo Recomendado',
    justification: 'Justificación',
    livePestMonitor: "Monitor de Plagas en Vivo",
    scanForPests: "Buscar Plagas",
    scanning: "Buscando...",
    activityLog: "Registro de Actividad",
    noPestsFound: "No se encontraron plagas en la vista actual.",
    startCamera: "Iniciar Cámara",
    pestIdentified: "identificado",
    actionSprayed: "Pesticida aplicado a las",
    automatedScanning: "Escaneo Automatizado",
    automatedSuggestion: "Sugerencia Automatizada",
    plantHealthAnalyst: "Analista de Salud Vegetal",
    plantHeight: "Altura de la Planta",
    leafCount: "Conteo de Hojas",
    soilTemperature: "Temp. del Suelo",
    analyzePlant: "Analizar Planta",
    analysisResults: "Resultados del Análisis",
    plantHealthStatus: "Estado de Salud de la Planta",
    growthStage: "Etapa de Crecimiento",
    stressFactors: "Factores de Estrés",
    recommendations: "Recomendaciones",
    growthTrends: "Tendencias de Crecimiento",
    errorAnalysis: "Error durante el análisis de la planta.",
    uploadOrCaptureImage: "Suba o capture una imagen de la planta para analizar.",
    soilHealthScore: "Puntuación de Salud del Suelo",
    poor: "Pobre",
    fair: "Regular",
    good: "Bueno",
    excellent: "Excelente",
    getScore: "Obtener Puntuación",
    generatingScore: "Generando puntuación...",
    errorScore: "No se pudo obtener la puntuación.",
    clickToGetScore: "Haga clic en actualizar para obtener una puntuación de salud del suelo calculada por IA.",
    automatedScore: "Puntuación Automatizada",
  },
  de: {
    appTitle: 'Agri-Intelli',
    exportCSV: 'CSV exportieren',
    exportPDF: 'PDF exportieren',
    fieldMapAnalysis: 'Feldkartenanalyse',
    vegetationIndices: 'Vegetationsindizes',
    keyMetrics: 'Schlüsselmetriken',
    activeAlerts: 'Aktive Warnungen',
    weatherForecast: 'Wettervorhersage',
    dailyActivityReport: 'Täglicher Aktivitätsbericht',
    aiCropSuggestion: 'KI-Erntevorschlag',
    noActiveAlerts: 'Keine aktiven Warnungen. Der Hof ist gesund.',
    highPestRisk: 'Hohes Schädlingsrisiko festgestellt',
    lowSoilMoisture: 'Geringe Bodenfeuchtigkeit festgestellt',
    avgSoilMoisture: 'Durchschn. Bodenfeuchtigkeit',
    avgNDVI: 'Durchschn. NDVI',
    canopyCover: 'Kronendachdeckung',
    cropGrowthStage: 'Wachstumsstadium der Ernte',
    daysAhead: 'Tage voraus',
    daysBehind: 'Tage im Rückstand',
    onSchedule: 'im Zeitplan',
    mapLayer: 'Kartenebene',
    none: 'Keine',
    soilMoisture: 'Bodenfeuchtigkeit',
    soilAnalysis: 'Bodenanalyse',
    pestRisk: 'Schädlingsrisiko',
    legendLow: 'Niedrig',
    legendHigh: 'Hoch',
    uploadImage: 'Bild hochladen',
    useCamera: 'Kamera verwenden',
    stopCamera: 'Kamera anhalten',
    capture: 'Erfassen',
    analyzing: 'Analysiere...',
    errorRecommendations: 'Vorschlag konnte nicht abgerufen werden.',
    loadingRecommendations: 'Vorschlag wird generiert...',
    clickRefreshSuggestion: 'Klicken Sie auf Aktualisieren, um einen KI-Erntevorschlag basierend auf den aktuellen Farmbedingungen zu erhalten.',
    refresh: 'Aktualisieren',
    farmConditions: 'Farmbedingungen',
    phLevel: 'pH-Wert',
    nutrients: 'Nährstoffe (N-P-K)',
    soilType: 'Bodentyp',
    climate: 'Klima',
    currentWeather: 'Aktuelles Wetter',
    temperature: 'Temperatur',
    humidity: 'Luftfeuchtigkeit',
    windSpeed: 'Windgeschwindigkeit',
    recommendedCrop: 'Empfohlene Feldfrucht',
    justification: 'Begründung',
    livePestMonitor: "Live-Schädlingsmonitor",
    scanForPests: "Nach Schädlingen scannen",
    scanning: "Scannen...",
    activityLog: "Aktivitätsprotokoll",
    noPestsFound: "In der aktuellen Ansicht wurden keine Schädlinge gefunden.",
    startCamera: "Kamera starten",
    pestIdentified: "identifiziert",
    actionSprayed: "Pestizid gesprüht um",
    automatedScanning: "Automatisches Scannen",
    automatedSuggestion: "Automatischer Vorschlag",
    plantHealthAnalyst: "Pflanzengesundheitsanalyst",
    plantHeight: "Pflanzenhöhe",
    leafCount: "Blattanzahl",
    soilTemperature: "Bodentemp.",
    analyzePlant: "Pflanze analysieren",
    analysisResults: "Analyseergebnisse",
    plantHealthStatus: "Pflanzengesundheitsstatus",
    growthStage: "Wachstumsstadium",
    stressFactors: "Stressfaktoren",
    recommendations: "Empfehlungen",
    growthTrends: "Wachstumstrends",
    errorAnalysis: "Fehler bei der Pflanzenanalyse.",
    uploadOrCaptureImage: "Laden Sie ein Bild der Pflanze hoch oder nehmen Sie es auf, um es zu analysieren.",
    soilHealthScore: "Bodengesundheits-Score",
    poor: "Schlecht",
    fair: "Mäßig",
    good: "Gut",
    excellent: "Ausgezeichnet",
    getScore: "Score abrufen",
    generatingScore: "Score wird generiert...",
    errorScore: "Score konnte nicht abgerufen werden.",
    clickToGetScore: "Klicken Sie auf Aktualisieren, um einen KI-berechneten Bodengesundheits-Score zu erhalten.",
    automatedScore: "Automatischer Score",
  },
  ja: {
    appTitle: 'アグリインテリ',
    exportCSV: 'CSVをエクスポート',
    exportPDF: 'PDFをエクスポート',
    fieldMapAnalysis: '圃場マップ分析',
    vegetationIndices: '植生指数',
    keyMetrics: '主要指標',
    activeAlerts: 'アクティブなアラート',
    weatherForecast: '天気予報',
    dailyActivityReport: '毎日の活動報告',
    aiCropSuggestion: 'AI作物提案',
    noActiveAlerts: 'アクティブなアラートはありません。農場は健全です。',
    highPestRisk: '高い害虫リスクが検出されました',
    lowSoilMoisture: '低い土壌水分が検出されました',
    avgSoilMoisture: '平均土壌水分',
    avgNDVI: '平均NDVI',
    canopyCover: 'キャノピーカバー',
    cropGrowthStage: '作物成長段階',
    daysAhead: '日進んでいます',
    daysBehind: '日遅れています',
    onSchedule: '予定通り',
    mapLayer: 'マップレイヤー',
    none: 'なし',
    soilMoisture: '土壌水分',
    soilAnalysis: '土壌分析',
    pestRisk: '害虫リスク',
    legendLow: '低い',
    legendHigh: '高い',
    uploadImage: '画像をアップロード',
    useCamera: 'カメラを使用',
    stopCamera: 'カメラを停止',
    capture: 'キャプチャ',
    analyzing: '分析中...',
    errorRecommendations: '提案を取得できませんでした。',
    loadingRecommendations: '提案を生成しています...',
    clickRefreshSuggestion: '更新をクリックして、現在の農場の状況に基づいたAIの作物提案を取得します。',
    refresh: '更新',
    farmConditions: '農場の状況',
    phLevel: 'pHレベル',
    nutrients: '栄養素 (N-P-K)',
    soilType: '土壌タイプ',
    climate: '気候',
    currentWeather: '現在の天気',
    temperature: '温度',
    humidity: '湿度',
    windSpeed: '風速',
    recommendedCrop: '推奨作物',
    justification: '理由',
    livePestMonitor: "ライブ害虫モニター",
    scanForPests: "害虫をスキャン",
    scanning: "スキャン中...",
    activityLog: "アクティビティログ",
    noPestsFound: "現在のビューでは害虫は見つかりませんでした。",
    startCamera: "カメラを開始",
    pestIdentified: "を識別しました",
    actionSprayed: "に農薬を散布しました",
    automatedScanning: "自動スキャン",
    automatedSuggestion: "自動提案",
    plantHealthAnalyst: "植物健康アナリスト",
    plantHeight: "植物の高さ",
    leafCount: "葉の数",
    soilTemperature: "地温",
    analyzePlant: "植物を分析",
    analysisResults: "分析結果",
    plantHealthStatus: "植物の健康状態",
    growthStage: "成長段階",
    stressFactors: "ストレス要因",
    recommendations: "推奨事項",
    growthTrends: "成長傾向",
    errorAnalysis: "植物の分析中にエラーが発生しました。",
    uploadOrCaptureImage: "分析する植物の画像をアップロードまたはキャプチャしてください。",
    soilHealthScore: "土壌健全性スコア",
    poor: "悪い",
    fair: "普通",
    good: "良い",
    excellent: "非常に良い",
    getScore: "スコアを取得",
    generatingScore: "スコアを生成中...",
    errorScore: "スコアを取得できませんでした。",
    clickToGetScore: "更新をクリックして、AIが計算した土壌健全性スコアを取得します。",
    automatedScore: "自動スコア",
  },
};


export const MOCK_WEATHER_FORECAST: (lang: Language) => WeatherForecast[] = (lang) => {
    const daysEn = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];
    const daysEs = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'];
    const daysDe = ['Mo', 'Di', 'Mi', 'Do', 'Fr'];
    const daysJa = ['月', '火', '水', '木', '金'];
    const days = { en: daysEn, es: daysEs, de: daysDe, ja: daysJa }[lang];
    return [
        { day: days[0], condition: WeatherCondition.Sunny, temp: 28 },
        { day: days[1], condition: WeatherCondition.Sunny, temp: 30 },
        { day: days[2], condition: WeatherCondition.Cloudy, temp: 26 },
        { day: days[3], condition: WeatherCondition.Rainy, temp: 24 },
        { day: days[4], condition: WeatherCondition.Sunny, temp: 29 },
    ];
};

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
    { id: 1, time: '08:15 AM', type: 'Scouting', location: 'Sector A2', details: 'Checked for aphids, minor presence.' },
    { id: 2, time: '10:30 AM', type: 'Irrigation', location: 'Sector B1', details: 'Ran sprinklers for 30 minutes.' },
    { id: 3, time: '01:00 PM', type: 'Fertilizer', location: 'Sector A1', details: 'Applied nitrogen-rich solution.' },
    { id: 4, time: '03:45 PM', type: 'Pesticide', location: 'Sector C3', details: 'Preventative spray for fungal growth.' },
    // FIX: Corrected typo from 'aype' to 'type' to match the ActivityLog interface.
    { id: 5, time: '05:00 PM', type: 'Scouting', location: 'Sector B2', details: 'No signs of new pest activity.' },
];
