import type { Language, ActivityLog, WeatherForecast } from './types';
import { WeatherCondition } from './types';

export const LANGUAGES: { key: Language; name: string }[] = [
  { key: 'en', name: 'English' },
  { key: 'es', name: 'Español' },
  { key: 'de', name: 'Deutsch' },
  { key: 'ja', name: '日本語' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'Agri-Intelli',
    suggestions: 'Suggestions',
    exportCSV: 'Export CSV',
    exportPDF: 'Export PDF',
    fieldMapAnalysis: 'Field Map Analysis',
    vegetationIndices: 'Vegetation Indices',
    keyMetrics: 'Key Metrics',
    activeAlerts: 'Active Alerts',
    weatherForecast: 'Weather Forecast',
    dailyActivityReport: 'Daily Activity Report',
    aiCropSuggestion: 'AI Crop Suggestion',
    noActiveAlerts: 'No active alerts. The farm is healthy.',
    highPestRisk: 'High pest risk detected',
    pestRiskMessage: 'High {pestType} risk detected',
    pestRiskAction: 'Action: Apply targeted pesticide spray in Sector {sector}.',
    lowSoilMoisture: 'Low soil moisture detected',
    lowSoilMoistureAction: 'Action: Increase irrigation cycle duration by 20% in Sector {sector}.',
    avgSoilMoisture: 'Avg. Soil Moisture',
    avgNDVI: 'Avg. NDVI',
    canopyCover: 'Canopy Cover',
    cropGrowthStage: 'Crop Growth Stage',
    daysAhead: 'days ahead',
    daysBehind: 'days behind',
    onSchedule: 'on schedule',
    mapLayer: 'Map Layer',
    none: 'None',
    soilMoisture: 'Soil Moisture',
    soilHealth: 'Soil Health',
    pestRisk: 'Pest Risk',
    legendLow: 'Low',
    legendHigh: 'High',
    uploadImage: 'Upload Image',
    useCamera: 'Use Camera',
    stopCamera: 'Stop Camera',
    capture: 'Capture',
    analyzing: 'Analyzing...',
    errorRecommendations: 'Could not fetch suggestion.',
    loadingRecommendations: 'Generating suggestion...',
    clickRefreshSuggestion: 'Click refresh to get an AI crop suggestion based on current farm conditions.',
    refresh: 'Refresh',
    farmConditions: 'Farm Conditions',
    phLevel: 'pH Level',
    nutrients: 'Nutrients (N-P-K)',
    soilType: 'Soil Type',
    climate: 'Climate',
    currentWeather: 'Current Weather',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    recommendedCrop: 'Recommended Crop',
    justification: 'Justification',
    livePestMonitor: "Live Pest Monitor",
    scanForPests: "Scan for Pests",
    scanning: "Scanning...",
    activityLog: "Activity Log",
    noPestsFound: "No pests found in the current view.",
    startCamera: "Start Camera",
    pestIdentified: "identified",
    actionSprayed: "Pesticide sprayed at",
    automatedScanning: "Automated Scanning",
    automatedSuggestion: "Automated Suggestion",
    plantHealthAnalyst: "Plant Health Analyst",
    plantHeight: "Plant Height",
    leafCount: "Leaf Count",
    soilTemperature: "Soil Temp.",
    analyzePlant: "Analyze Plant",
    analysisResults: "Analysis Results",
    plantHealthStatus: "Plant Health Status",
    growthStage: "Growth Stage",
    stressFactors: "Stress Factors",
    recommendations: "Recommendations",
    growthTrends: "Growth Trends",
    errorAnalysis: "Error during plant analysis.",
    uploadOrCaptureImage: "Upload or capture an image of the plant to analyze.",
    soilHealthScore: "Soil Health Score",
    poor: "Poor",
    fair: "Fair",
    good: "Good",
    excellent: "Excellent",
    getScore: "Get Score",
    generatingScore: "Generating score...",
    errorScore: "Could not fetch score.",
    clickToGetScore: "Click refresh to get an AI-calculated soil health score.",
    automatedScore: "Automated Score",
    actionableAdvice: 'Actionable Advice',
    cameraModuleAutomation: 'Camera Module Automation',
    automatic: 'Automatic',
    manual: 'Manual',
    off: 'Off',
    startTime: 'Start Time',
    endTime: 'End Time',
    cameraStatus: 'Camera Status',
    deployed: 'Deployed',
    docked: 'Docked',
    inactive: 'Inactive',
    deployCamera: 'Deploy Camera',
    dockCamera: 'Dock Camera',
    deploying: 'Deploying...',
    docking: 'Docking...',
    statusReason_GoodWeather: 'Weather condition is favorable for deployment.',
    statusReason_BadWeather: 'Weather is unsafe. Deployment suspended.',
    statusReason_OffSchedule: 'Outside of scheduled operating hours.',
    statusReason_Manual: 'Manual control engaged. Awaiting command.',
    statusReason_Off: 'System is turned off.',
    predictiveAnalytics: 'Predictive Analytics',
    aiWeatherForecast: 'AI Weather Forecast',
    pestRiskForecast: 'Pest Risk Forecast',
    yieldPrediction: 'Yield Prediction',
    estimatedYield: 'Estimated Yield',
    tonsPerAcre: 'tons/acre',
    riskLevel: 'Risk Level',
    predictionFactors: 'Prediction Factors',
    yieldFactorGoodNDVI: 'Strong NDVI values indicate healthy vegetation.',
    yieldFactorGoodWeather: 'Favorable weather forecast for coming weeks.',
    yieldFactorLowPest: 'Low historical and predicted pest pressure.',
    liveMarketPrices: 'Live Market Prices',
    priceINR: 'Price (INR)',
    perQuintal: 'per quintal',
    wheat: 'Wheat',
    tomato: 'Tomato',
    cotton: 'Cotton',
    sugarcane: 'Sugarcane',
    weatherSafe: 'Weather is safe',
    weatherUnsafe: 'Unsafe weather!',
    deploymentDisabled: 'Deployment disabled due to unsafe weather.',
    unsafeWeatherWarning: 'Warning: Current weather conditions ({condition}) are unsafe for camera deployment. It is recommended to keep the module docked to prevent damage.',
    Sunny: 'Sunny',
    Cloudy: 'Cloudy',
    Rainy: 'Rainy',
    Stormy: 'Stormy',
    irrigationControl: 'Irrigation Control',
    irrigating: 'Irrigating',
    suspended: 'Suspended',
    idle: 'Idle',
    startIrrigation: 'Start Irrigation',
    stopIrrigation: 'Stop Irrigation',
    statusReason_Rain: 'Irrigation suspended due to rain.',
    statusReason_Saturated: 'Soil moisture is sufficient. Irrigation paused.',
    statusReason_Scheduled: 'Automatic irrigation schedule is active.',
    statusReason_ManualOn: 'Manual irrigation active.',
    statusReason_ManualOff: 'Awaiting manual command.',
    rainWarning: 'Cannot start: it is currently raining.',
    saturatedWarning: 'Cannot start: soil is already saturated.',
    aiPestIdentifier: 'AI Pest Identifier',
    analyzeImage: 'Analyze Image',
    errorPestId: 'Error during pest identification.',
    noPestDetected: 'No pest detected in the image.',
    pestIdentificationResult: 'Pest Identification Result',
    pestName: 'Pest Name',
    treatmentRecommendation: 'Treatment Recommendation',
    lowNutrientWarningTitle: 'Low Nutrient Levels',
    lowNutrientWarningMessage: 'Levels for {nutrients} are low. Consider applying fertilizer to prevent yield loss.',
    Nitrogen: 'Nitrogen',
    Phosphorus: 'Phosphorus',
    Potassium: 'Potassium',
    cameraDisabled: 'Camera functionality is not enabled for this application.',
  },
  es: {
    appTitle: 'Agri-Intelli',
    suggestions: 'Sugerencias',
    exportCSV: 'Exportar CSV',
    exportPDF: 'Exportar PDF',
    fieldMapAnalysis: 'Análisis del Mapa de Campo',
    vegetationIndices: 'Índices de Vegetación',
    keyMetrics: 'Métricas Clave',
    activeAlerts: 'Alertas Activas',
    weatherForecast: 'Pronóstico del Tiempo',
    dailyActivityReport: 'Informe de Actividad Diaria',
    aiCropSuggestion: 'Sugerencia de Cultivo por IA',
    noActiveAlerts: 'No hay alertas activas. La granja está sana.',
    highPestRisk: 'Alto riesgo de plagas detectado',
    pestRiskMessage: 'Alto riesgo de {pestType} detectado',
    pestRiskAction: 'Acción: Aplicar pesticida específico en el Sector {sector}.',
    lowSoilMoisture: 'Baja humedad del suelo detectada',
    lowSoilMoistureAction: 'Acción: Aumentar la duración del ciclo de riego en un 20% en el Sector {sector}.',
    avgSoilMoisture: 'Humedad Media del Suelo',
    avgNDVI: 'NDVI Medio',
    canopyCover: 'Cobertura del Dosel',
    cropGrowthStage: 'Etapa de Crecimiento del Cultivo',
    daysAhead: 'días de adelanto',
    daysBehind: 'días de atraso',
    onSchedule: 'según lo previsto',
    mapLayer: 'Capa del Mapa',
    none: 'Ninguna',
    soilMoisture: 'Humedad del Suelo',
    soilHealth: 'Salud del Suelo',
    pestRisk: 'Riesgo de Plagas',
    legendLow: 'Bajo',
    legendHigh: 'Alto',
    uploadImage: 'Subir Imagen',
    useCamera: 'Usar Cámara',
    stopCamera: 'Detener Cámara',
    capture: 'Capturar',
    analyzing: 'Analizando...',
    errorRecommendations: 'No se pudo obtener la sugerencia.',
    loadingRecommendations: 'Generando sugerencia...',
    clickRefreshSuggestion: 'Haga clic en actualizar para obtener una sugerencia de cultivo de IA basada en las condiciones actuales de la granja.',
    refresh: 'Actualizar',
    farmConditions: 'Condiciones de la Granja',
    phLevel: 'Nivel de pH',
    nutrients: 'Nutrientes (N-P-K)',
    soilType: 'Tipo de Suelo',
    climate: 'Clima',
    currentWeather: 'Clima Actual',
    temperature: 'Temperatura',
    humidity: 'Humedad',
    windSpeed: 'Velocidad del Viento',
    recommendedCrop: 'Cultivo Recomendado',
    justification: 'Justificación',
    livePestMonitor: "Monitor de Plagas en Vivo",
    scanForPests: "Buscar Plagas",
    scanning: "Buscando...",
    activityLog: "Registro de Actividad",
    noPestsFound: "No se encontraron plagas en la vista actual.",
    startCamera: "Iniciar Cámara",
    pestIdentified: "identificado",
    actionSprayed: "Pesticida aplicado a las",
    automatedScanning: "Escaneo Automatizado",
    automatedSuggestion: "Sugerencia Automatizada",
    plantHealthAnalyst: "Analista de Salud Vegetal",
    plantHeight: "Altura de la Planta",
    leafCount: "Conteo de Hojas",
    soilTemperature: "Temp. del Suelo",
    analyzePlant: "Analizar Planta",
    analysisResults: "Resultados del Análisis",
    plantHealthStatus: "Estado de Salud de la Planta",
    growthStage: "Etapa de Crecimiento",
    stressFactors: "Factores de Estrés",
    recommendations: "Recomendaciones",
    growthTrends: "Tendencias de Crecimiento",
    errorAnalysis: "Error durante el análisis de la planta.",
    uploadOrCaptureImage: "Suba o capture una imagen de la planta para analizar.",
    soilHealthScore: "Puntuación de Salud del Suelo",
    poor: "Pobre",
    fair: "Regular",
    good: "Bueno",
    excellent: "Excelente",
    getScore: "Obtener Puntuación",
    generatingScore: "Generando puntuación...",
    errorScore: "No se pudo obtener la puntuación.",
    clickToGetScore: "Haga clic en actualizar para obtener una puntuación de salud del suelo calculada por IA.",
    automatedScore: "Puntuación Automatizada",
    actionableAdvice: 'Consejo Práctico',
    cameraModuleAutomation: 'Automatización del Módulo de Cámara',
    automatic: 'Automático',
    manual: 'Manual',
    off: 'Apagado',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    cameraStatus: 'Estado de la Cámara',
    deployed: 'Desplegada',
    docked: 'Acoplada',
    inactive: 'Inactiva',
    deployCamera: 'Desplegar Cámara',
    dockCamera: 'Acoplar Cámara',
    deploying: 'Desplegando...',
    docking: 'Acoplando...',
    statusReason_GoodWeather: 'La condición climática es favorable para el despliegue.',
    statusReason_BadWeather: 'El clima no es seguro. Despliegue suspendido.',
    statusReason_OffSchedule: 'Fuera del horario de funcionamiento programado.',
    statusReason_Manual: 'Control manual activado. Esperando comando.',
    statusReason_Off: 'El sistema está apagado.',
    predictiveAnalytics: 'Análisis Predictivo',
    aiWeatherForecast: 'Pronóstico del Tiempo IA',
    pestRiskForecast: 'Pronóstico de Riesgo de Plagas',
    yieldPrediction: 'Predicción de Rendimiento',
    estimatedYield: 'Rendimiento Estimado',
    tonsPerAcre: 'ton/acre',
    riskLevel: 'Nivel de Riesgo',
    predictionFactors: 'Factores de Predicción',
    yieldFactorGoodNDVI: 'Valores NDVI fuertes indican vegetación saludable.',
    yieldFactorGoodWeather: 'Pronóstico del tiempo favorable para las próximas semanas.',
    yieldFactorLowPest: 'Baja presión de plagas histórica y prevista.',
    liveMarketPrices: 'Precios de Mercado en Vivo',
    priceINR: 'Precio (INR)',
    perQuintal: 'por quintal',
    wheat: 'Trigo',
    tomato: 'Tomate',
    cotton: 'Algodón',
    sugarcane: 'Caña de azúcar',
    weatherSafe: 'Clima seguro',
    weatherUnsafe: '¡Clima inseguro!',
    deploymentDisabled: 'Despliegue deshabilitado por clima inseguro.',
    unsafeWeatherWarning: 'Advertencia: Las condiciones climáticas actuales ({condition}) no son seguras para el despliegue de la cámara. Se recomienda mantener el módulo acoplado para evitar daños.',
    Sunny: 'Soleado',
    Cloudy: 'Nublado',
    Rainy: 'Lluvioso',
    Stormy: 'Tormentoso',
    irrigationControl: 'Control de Riego',
    irrigating: 'Regando',
    suspended: 'Suspendido',
    idle: 'Inactivo',
    startIrrigation: 'Iniciar Riego',
    stopIrrigation: 'Detener Riego',
    statusReason_Rain: 'Riego suspendido por lluvia.',
    statusReason_Saturated: 'Humedad del suelo suficiente. Riego en pausa.',
    statusReason_Scheduled: 'Programa de riego automático activo.',
    statusReason_ManualOn: 'Riego manual activo.',
    statusReason_ManualOff: 'Esperando comando manual.',
    rainWarning: 'No se puede iniciar: está lloviendo.',
    saturatedWarning: 'No se puede iniciar: el suelo ya está saturado.',
    aiPestIdentifier: 'Identificador de Plagas IA',
    analyzeImage: 'Analizar Imagen',
    errorPestId: 'Error durante la identificación de plagas.',
    noPestDetected: 'No se detectó ninguna plaga en la imagen.',
    pestIdentificationResult: 'Resultado de Identificación de Plagas',
    pestName: 'Nombre de la Plaga',
    treatmentRecommendation: 'Recomendación de Tratamiento',
    lowNutrientWarningTitle: 'Niveles Bajos de Nutrientes',
    lowNutrientWarningMessage: 'Los niveles de {nutrients} son bajos. Considere aplicar fertilizante para prevenir la pérdida de rendimiento.',
    Nitrogen: 'Nitrógeno',
    Phosphorus: 'Fósforo',
    Potassium: 'Potasio',
    cameraDisabled: 'La funcionalidad de la cámara no está habilitada para esta aplicación.',
  },
  de: {
    appTitle: 'Agri-Intelli',
    suggestions: 'Vorschläge',
    exportCSV: 'CSV exportieren',
    exportPDF: 'PDF exportieren',
    fieldMapAnalysis: 'Feldkartenanalyse',
    vegetationIndices: 'Vegetationsindizes',
    keyMetrics: 'Schlüsselmetriken',
    activeAlerts: 'Aktive Warnungen',
    weatherForecast: 'Wettervorhersage',
    dailyActivityReport: 'Täglicher Aktivitätsbericht',
    aiCropSuggestion: 'KI-Erntevorschlag',
    noActiveAlerts: 'Keine aktiven Warnungen. Der Hof ist gesund.',
    highPestRisk: 'Hohes Schädlingsrisiko festgestellt',
    pestRiskMessage: 'Hohes Risiko für {pestType} festgestellt',
    pestRiskAction: 'Aktion: Gezieltes Pestizidspray in Sektor {sector} anwenden.',
    lowSoilMoisture: 'Geringe Bodenfeuchtigkeit festgestellt',
    lowSoilMoistureAction: 'Aktion: Bewässerungszyklusdauer in Sektor {sector} um 20% erhöhen.',
    avgSoilMoisture: 'Durchschn. Bodenfeuchtigkeit',
    avgNDVI: 'Durchschn. NDVI',
    canopyCover: 'Kronendachdeckung',
    cropGrowthStage: 'Wachstumsstadium der Ernte',
    daysAhead: 'Tage voraus',
    daysBehind: 'Tage im Rückstand',
    onSchedule: 'im Zeitplan',
    mapLayer: 'Kartenebene',
    none: 'Keine',
    soilMoisture: 'Bodenfeuchtigkeit',
    soilHealth: 'Bodengesundheit',
    pestRisk: 'Schädlingsrisiko',
    legendLow: 'Niedrig',
    legendHigh: 'Hoch',
    uploadImage: 'Bild hochladen',
    useCamera: 'Kamera verwenden',
    stopCamera: 'Kamera anhalten',
    capture: 'Erfassen',
    analyzing: 'Analysiere...',
    errorRecommendations: 'Vorschlag konnte nicht abgerufen werden.',
    loadingRecommendations: 'Vorschlag wird generiert...',
    clickRefreshSuggestion: 'Klicken Sie auf Aktualisieren, um einen KI-Erntevorschlag basierend auf den aktuellen Farmbedingungen zu erhalten.',
    refresh: 'Aktualisieren',
    farmConditions: 'Farmbedingungen',
    phLevel: 'pH-Wert',
    nutrients: 'Nährstoffe (N-P-K)',
    soilType: 'Bodentyp',
    climate: 'Klima',
    currentWeather: 'Aktuelles Wetter',
    temperature: 'Temperatur',
    humidity: 'Luftfeuchtigkeit',
    windSpeed: 'Windgeschwindigkeit',
    recommendedCrop: 'Empfohlene Feldfrucht',
    justification: 'Begründung',
    livePestMonitor: "Live-Schädlingsmonitor",
    scanForPests: "Nach Schädlingen scannen",
    scanning: "Scannen...",
    activityLog: "Aktivitätsprotokoll",
    noPestsFound: "In der aktuellen Ansicht wurden keine Schädlinge gefunden.",
    startCamera: "Kamera starten",
    pestIdentified: "identifiziert",
    actionSprayed: "Pestizid gesprüht um",
    automatedScanning: "Automatisches Scannen",
    automatedSuggestion: "Automatischer Vorschlag",
    plantHealthAnalyst: "Pflanzengesundheitsanalyst",
    plantHeight: "Pflanzenhöhe",
    leafCount: "Blattanzahl",
    soilTemperature: "Bodentemp.",
    analyzePlant: "Pflanze analysieren",
    analysisResults: "Analyseergebnisse",
    plantHealthStatus: "Pflanzengesundheitsstatus",
    growthStage: "Wachstumsstadium",
    stressFactors: "Stressfaktoren",
    recommendations: "Empfehlungen",
    growthTrends: "Wachstumstrends",
    errorAnalysis: "Fehler bei der Pflanzenanalyse.",
    uploadOrCaptureImage: "Laden Sie ein Bild der Pflanze hoch oder nehmen Sie es auf, um es zu analysieren.",
    soilHealthScore: "Bodengesundheits-Score",
    poor: "Schlecht",
    fair: "Mäßig",
    good: "Gut",
    excellent: "Ausgezeichnet",
    getScore: "Score abrufen",
    generatingScore: "Score wird generiert...",
    errorScore: "Score konnte nicht abgerufen werden.",
    clickToGetScore: "Klicken Sie auf Aktualisieren, um einen KI-berechneten Bodengesundheits-Score zu erhalten.",
    automatedScore: "Automatischer Score",
    actionableAdvice: 'Handlungsempfehlung',
    cameraModuleAutomation: 'Kameramodul-Automatisierung',
    automatic: 'Automatisch',
    manual: 'Manuell',
    off: 'Aus',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    cameraStatus: 'Kamerastatus',
    deployed: 'Ausgefahren',
    docked: 'Angedockt',
    inactive: 'Inaktiv',
    deployCamera: 'Kamera ausfahren',
    dockCamera: 'Kamera Andocken',
    deploying: 'Fahre aus...',
    docking: 'Docke an...',
    statusReason_GoodWeather: 'Wetterbedingungen sind günstig für den Einsatz.',
    statusReason_BadWeather: 'Wetter ist unsicher. Einsatz ausgesetzt.',
    statusReason_OffSchedule: 'Außerhalb der geplanten Betriebszeiten.',
    statusReason_Manual: 'Manuelle Steuerung aktiviert. Warte auf Befehl.',
    statusReason_Off: 'System ist ausgeschaltet.',
    predictiveAnalytics: 'Prädiktive Analytik',
    aiWeatherForecast: 'KI-Wettervorhersage',
    pestRiskForecast: 'Schädlingsrisikovorhersage',
    yieldPrediction: 'Ertragsvorhersage',
    estimatedYield: 'Geschätzter Ertrag',
    tonsPerAcre: 't/ha',
    riskLevel: 'Risikostufe',
    predictionFactors: 'Vorhersagefaktoren',
    yieldFactorGoodNDVI: 'Starke NDVI-Werte deuten auf eine gesunde Vegetation hin.',
    yieldFactorGoodWeather: 'Günstige Wettervorhersage für die kommenden Wochen.',
    yieldFactorLowPest: 'Niedriger historischer und prognostizierter Schädlingsdruck.',
    liveMarketPrices: 'Live-Marktpreise',
    priceINR: 'Preis (INR)',
    perQuintal: 'pro Doppelzentner',
    wheat: 'Weizen',
    tomato: 'Tomate',
    cotton: 'Baumwolle',
    sugarcane: 'Zuckerrohr',
    weatherSafe: 'Wetter ist sicher',
    weatherUnsafe: 'Unsicheres Wetter!',
    deploymentDisabled: 'Einsatz wegen unsicheren Wetters deaktiviert.',
    unsafeWeatherWarning: 'Warnung: Die aktuellen Wetterbedingungen ({condition}) sind für den Einsatz der Kamera unsicher. Es wird empfohlen, das Modul angedockt zu lassen, um Schäden zu vermeiden.',
    Sunny: 'Sonnig',
    Cloudy: 'Bewölkt',
    Rainy: 'Regnerisch',
    Stormy: 'Stürmisch',
    irrigationControl: 'Bewässerungssteuerung',
    irrigating: 'Bewässert',
    suspended: 'Ausgesetzt',
    idle: 'Leerlauf',
    startIrrigation: 'Bewässerung starten',
    stopIrrigation: 'Bewässerung stoppen',
    statusReason_Rain: 'Bewässerung wegen Regen ausgesetzt.',
    statusReason_Saturated: 'Bodenfeuchtigkeit ist ausreichend. Bewässerung pausiert.',
    statusReason_Scheduled: 'Automatischer Bewässerungsplan ist aktiv.',
    statusReason_ManualOn: 'Manuelle Bewässerung aktiv.',
    statusReason_ManualOff: 'Warte auf manuellen Befehl.',
    rainWarning: 'Start nicht möglich: es regnet gerade.',
    saturatedWarning: 'Start nicht möglich: Boden ist bereits gesättigt.',
    aiPestIdentifier: 'KI-Schädlingserkennung',
    analyzeImage: 'Bild analysieren',
    errorPestId: 'Fehler bei der Schädlingserkennung.',
    noPestDetected: 'Kein Schädling im Bild erkannt.',
    pestIdentificationResult: 'Ergebnis der Schädlingserkennung',
    pestName: 'Schädlingsname',
    treatmentRecommendation: 'Behandlungsempfehlung',
    lowNutrientWarningTitle: 'Niedrige Nährstoffwerte',
    lowNutrientWarningMessage: 'Die Werte für {nutrients} sind niedrig. Erwägen Sie die Anwendung von Dünger, um Ertragsverluste zu vermeiden.',
    Nitrogen: 'Stickstoff',
    Phosphorus: 'Phosphor',
    Potassium: 'Kalium',
    cameraDisabled: 'Die Kamerafunktion ist für diese Anwendung nicht aktiviert.',
  },
  ja: {
    appTitle: 'アグリインテリ',
    suggestions: '提案',
    exportCSV: 'CSVをエクスポート',
    exportPDF: 'PDFをエクスポート',
    fieldMapAnalysis: '圃場マップ分析',
    vegetationIndices: '植生指数',
    keyMetrics: '主要指標',
    activeAlerts: 'アクティブなアラート',
    weatherForecast: '天気予報',
    dailyActivityReport: '毎日の活動報告',
    aiCropSuggestion: 'AI作物提案',
    noActiveAlerts: 'アクティブなアラートはありません。農場は健全です。',
    highPestRisk: '高い害虫リスクが検出されました',
    pestRiskMessage: '高い{pestType}のリスクが検出されました',
    pestRiskAction: 'アクション：セクター{sector}で対象を絞った農薬散布を実施してください。',
    lowSoilMoisture: '低い土壌水分が検出されました',
    lowSoilMoistureAction: 'アクション：セクター{sector}での灌漑サイクル時間を20％増やしてください。',
    avgSoilMoisture: '平均土壌水分',
    avgNDVI: '平均NDVI',
    canopyCover: 'キャノピーカバー',
    cropGrowthStage: '作物成長段階',
    daysAhead: '日進んでいます',
    daysBehind: '日遅れています',
    onSchedule: '予定通り',
    mapLayer: 'マップレイヤー',
    none: 'なし',
    soilMoisture: '土壌水分',
    soilHealth: '土壌の健康状態',
    pestRisk: '害虫リスク',
    legendLow: '低い',
    legendHigh: '高い',
    uploadImage: '画像をアップロード',
    useCamera: 'カメラを使用',
    stopCamera: 'カメラを停止',
    capture: 'キャプチャ',
    analyzing: '分析中...',
    errorRecommendations: '提案を取得できませんでした。',
    loadingRecommendations: '提案を生成しています...',
    clickRefreshSuggestion: '更新をクリックして、現在の農場の状況に基づいたAIの作物提案を取得します。',
    refresh: '更新',
    farmConditions: '農場の状況',
    phLevel: 'pHレベル',
    nutrients: '栄養素 (N-P-K)',
    soilType: '土壌タイプ',
    climate: '気候',
    currentWeather: '現在の天気',
    temperature: '温度',
    humidity: '湿度',
    windSpeed: '風速',
    recommendedCrop: '推奨作物',
    justification: '理由',
    livePestMonitor: "ライブ害虫モニター",
    scanForPests: "害虫をスキャン",
    scanning: "スキャン中...",
    activityLog: "アクティビティログ",
    noPestsFound: "現在のビューでは害虫は見つかりませんでした。",
    startCamera: "カメラを開始",
    pestIdentified: "を識別しました",
    actionSprayed: "に農薬を散布しました",
    automatedScanning: "自動スキャン",
    automatedSuggestion: "自動提案",
    plantHealthAnalyst: "植物健康アナリスト",
    plantHeight: "植物の高さ",
    leafCount: "葉の数",
    soilTemperature: "地温",
    analyzePlant: "植物を分析",
    analysisResults: "分析結果",
    plantHealthStatus: "植物の健康状態",
    growthStage: "成長段階",
    stressFactors: "ストレス要因",
    recommendations: "推奨事項",
    growthTrends: "成長傾向",
    errorAnalysis: "植物の分析中にエラーが発生しました。",
    uploadOrCaptureImage: "分析する植物の画像をアップロードまたはキャプチャしてください。",
    soilHealthScore: "土壌健全性スコア",
    poor: "悪い",
    fair: "普通",
    good: "良い",
    excellent: "非常に良い",
    getScore: "スコアを取得",
    generatingScore: "スコアを生成中...",
    errorScore: "スコアを取得できませんでした。",
    clickToGetScore: "更新をクリックして、AIが計算した土壌健全性スコアを取得します。",
    automatedScore: "自動スコア",
    actionableAdvice: '実践的なアドバイス',
    cameraModuleAutomation: 'カメラモジュール自動化',
    automatic: '自動',
    manual: '手動',
    off: 'オフ',
    startTime: '開始時間',
    endTime: '終了時間',
    cameraStatus: 'カメラの状態',
    deployed: '展開済み',
    docked: 'ドッキング済み',
    inactive: '非アクティブ',
    deployCamera: 'カメラを展開',
    dockCamera: 'カメラをドック',
    deploying: '展開中...',
    docking: 'ドッキング中...',
    statusReason_GoodWeather: '気象条件は展開に適しています。',
    statusReason_BadWeather: '天候が危険です。展開は中断されました。',
    statusReason_OffSchedule: '予定された稼働時間外です。',
    statusReason_Manual: '手動制御が有効です。コマンドを待っています。',
    statusReason_Off: 'システムはオフになっています。',
    predictiveAnalytics: '予測分析',
    aiWeatherForecast: 'AI天気予報',
    pestRiskForecast: '害虫リスク予測',
    yieldPrediction: '収穫量予測',
    estimatedYield: '推定収穫量',
    tonsPerAcre: 'トン/エーカー',
    riskLevel: 'リスクレベル',
    predictionFactors: '予測要因',
    yieldFactorGoodNDVI: 'NDVI値が高いことは、健全な植生を示しています。',
    yieldFactorGoodWeather: '今後数週間の好ましい天気予報。',
    yieldFactorLowPest: '過去および予測される害虫の圧力が低い。',
    liveMarketPrices: 'ライブ市場価格',
    priceINR: '価格 (INR)',
    perQuintal: 'キンタルあたり',
    wheat: '小麦',
    tomato: 'トマト',
    cotton: '綿',
    sugarcane: 'サトウキビ',
    weatherSafe: '天候は安全です',
    weatherUnsafe: '危険な天候です！',
    deploymentDisabled: '危険な天候のため、展開は無効になっています。',
    unsafeWeatherWarning: '警告: 現在の気象条件（{condition}）はカメラの展開には危険です。損傷を防ぐため、モジュールをドッキングしておくことをお勧めします。',
    Sunny: '晴れ',
    Cloudy: '曇り',
    Rainy: '雨',
    Stormy: '嵐',
    irrigationControl: '灌漑制御',
    irrigating: '灌漑中',
    suspended: '一時停止',
    idle: '待機中',
    startIrrigation: '灌漑開始',
    stopIrrigation: '灌漑停止',
    statusReason_Rain: '降雨のため灌漑を一時停止しました。',
    statusReason_Saturated: '土壌水分が十分です。灌漑は一時停止しました。',
    statusReason_Scheduled: '自動灌漑スケジュールが有効です。',
    statusReason_ManualOn: '手動灌漑が有効です。',
    statusReason_ManualOff: '手動コマンドを待っています。',
    rainWarning: '開始できません：現在雨が降っています。',
    saturatedWarning: '開始できません：土壌はすでに飽和状態です。',
    aiPestIdentifier: 'AI害虫識別',
    analyzeImage: '画像を分析',
    errorPestId: '害虫の識別中にエラーが発生しました。',
    noPestDetected: '画像から害虫は検出されませんでした。',
    pestIdentificationResult: '害虫識別結果',
    pestName: '害虫名',
    treatmentRecommendation: '治療の推奨',
    lowNutrientWarningTitle: '栄養素レベルの低下',
    lowNutrientWarningMessage: '{nutrients}のレベルが低下しています。収穫量の損失を防ぐために肥料の施用を検討してください。',
    Nitrogen: '窒素',
    Phosphorus: 'リン',
    Potassium: 'カリウム',
    cameraDisabled: 'このアプリケーションではカメラ機能は有効になっていません。',
  },
};

// FIX: Added missing MOCK_WEATHER_FORECAST function to resolve import error.
const getDayName = (lang: Language, dayOffset: number): string => {
    const date = new Date();
    date.setDate(date.getDate() + dayOffset);
    const days: Record<Language, string[]> = {
        en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        es: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
        de: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
        ja: ['日', '月', '火', '水', '木', '金', '土'],
    };
    return days[lang][date.getDay()];
};

export const MOCK_WEATHER_FORECAST = (lang: Language): WeatherForecast[] => [
  { day: getDayName(lang, 0), condition: WeatherCondition.Sunny, temp: 28 },
  { day: getDayName(lang, 1), condition: WeatherCondition.Sunny, temp: 29 },
  { day: getDayName(lang, 2), condition: WeatherCondition.Cloudy, temp: 26 },
  { day: getDayName(lang, 3), condition: WeatherCondition.Rainy, temp: 22 },
  { day: getDayName(lang, 4), condition: WeatherCondition.Sunny, temp: 25 },
];


export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
    { id: 1, time: '08:15 AM', type: 'Scouting', location: 'Sector A2', details: 'Checked for aphids, minor presence.' },
    { id: 2, time: '10:30 AM', type: 'Irrigation', location: 'Sector B1', details: 'Ran sprinklers for 30 minutes.' },
    { id: 3, time: '01:00 PM', type: 'Fertilizer', location: 'Sector A1', details: 'Applied nitrogen-rich solution.' },
    { id: 4, time: '03:45 PM', type: 'Pesticide', location: 'Sector C3', details: 'Preventative spray for fungal growth.' },
    // FIX: Corrected typo from 'aype' to 'type' to match the ActivityLog interface.
    { id: 5, time: '05:00 PM', type: 'Scouting', location: 'Sector B2', details: 'No signs of new pest activity.' },
];